# Generated by Django 2.1.5 on 2019-02-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('points', models.PositiveIntegerField(default=0)),
                ('lql', models.PositiveIntegerField(default=1)),
                ('time', models.DateTimeField(default=None)),
            ],
        ),
    ]
