# Generated by Django 2.1.5 on 2019-02-09 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer_stud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
