# Generated by Django 2.1.5 on 2019-02-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190209_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
